'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ViVeTool_GUI.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Friend ReadOnly Property about() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("about", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die A Network Exception occurred ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_ANetworkExceptionOccurred() As String
            Get
                Return ResourceManager.GetString("Error_ANetworkExceptionOccurred", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die An unknown Exception occurred ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_AnUnknownExceptionOccurred() As String
            Get
                Return ResourceManager.GetString("Error_AnUnknownExceptionOccurred", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Collapse Exception ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_CollapseException() As String
            Get
                Return ResourceManager.GetString("Error_CollapseException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Copies the Exception to the Clipboard and closes the dialog ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_CopyExceptionAndClose_ToolTip() As String
            Get
                Return ResourceManager.GetString("Error_CopyExceptionAndClose_ToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_Error() As String
            Get
                Return ResourceManager.GetString("Error_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die An Exception occurred while trying to set Feature ID {0} to {1} ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_ExceptionSettingFeatureID() As String
            Get
                Return ResourceManager.GetString("Error_ExceptionSettingFeatureID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die An Error occurred while trying to start the ViVeTool GUI Feature Scanner. ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_FeatureScannerNotFound1() As String
            Get
                Return ResourceManager.GetString("Error_FeatureScannerNotFound1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die The File doesn&apos;t exist. ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_FeatureScannerNotFound2() As String
            Get
                Return ResourceManager.GetString("Error_FeatureScannerNotFound2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die A generic Win32 Exception occurred. ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_GenericWin32Exception_Heading() As String
            Get
                Return ResourceManager.GetString("Error_GenericWin32Exception_Heading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die There could be multiple causes for Win32 Exceptions, but they usually narrow down to Anti-virus Software interfering with ViVeTool GUI, or Permission problems. ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_GenericWin32Exception_Text() As String
            Get
                Return ResourceManager.GetString("Error_GenericWin32Exception_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Network Error ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_NetworkError() As String
            Get
                Return ResourceManager.GetString("Error_NetworkError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Your IP may have been temporarily rate limited by the GitHub API for an hour. ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_NetworkException_GithubAPI() As String
            Get
                Return ResourceManager.GetString("Error_NetworkException_GithubAPI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die GitHub API Response:  ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_NetworkException_GithubAPI_Response() As String
            Get
                Return ResourceManager.GetString("Error_NetworkException_GithubAPI_Response", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ViVeTool-GUI is unable to populate the Build Combo Box, if the Device isn&apos;t connected to the Internet, or if the GitHub API is unreachable. ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_NetworkExceptionDetail1() As String
            Get
                Return ResourceManager.GetString("Error_NetworkExceptionDetail1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You are still able to manually change a Feature ID by pressing F12, and able to load a local Feature List. ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_NetworkExceptionDetail2() As String
            Get
                Return ResourceManager.GetString("Error_NetworkExceptionDetail2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Network Functions disabled. Press F12 to manually change a Feature. ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_NetworkFunctionsDisabledF12() As String
            Get
                Return ResourceManager.GetString("Error_NetworkFunctionsDisabledF12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Select Build 17704 or higher to use Grouping ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_SelectBuild17704OrHigherToUseGrouping() As String
            Get
                Return ResourceManager.GetString("Error_SelectBuild17704OrHigherToUseGrouping", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die An Error occurred while trying to set {0} to {1} ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_SetConfig() As String
            Get
                Return ResourceManager.GetString("Error_SetConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die An Error occurred while setting a feature configuration for {0} ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_SettingFeatureConfig() As String
            Get
                Return ResourceManager.GetString("Error_SettingFeatureConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Show Exception ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_ShowException() As String
            Get
                Return ResourceManager.GetString("Error_ShowException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  An Error occurred ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_Spaced_AnErrorOccurred() As String
            Get
                Return ResourceManager.GetString("Error_Spaced_AnErrorOccurred", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  A Network Exception occurred ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_Spaced_ANetworkExceptionOccurred() As String
            Get
                Return ResourceManager.GetString("Error_Spaced_ANetworkExceptionOccurred", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  An Exception occurred ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_Spaced_AnExceptionOccurred() As String
            Get
                Return ResourceManager.GetString("Error_Spaced_AnExceptionOccurred", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  Unsupported Build ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_Spaced_UnsupportedBuild() As String
            Get
                Return ResourceManager.GetString("Error_Spaced_UnsupportedBuild", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Unsupported Build ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_UnsupportedBuild() As String
            Get
                Return ResourceManager.GetString("Error_UnsupportedBuild", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You are running an unsupported Windows 10 Build. ViVe, ViVeTool and ViVeTool-GUI require Windows 10 Build 18963 or higher. Your Build is:  ähnelt.
        '''</summary>
        Friend ReadOnly Property Error_UnsupportedBuild_Text() As String
            Get
                Return ResourceManager.GetString("Error_UnsupportedBuild_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Always Disabled ähnelt.
        '''</summary>
        Friend ReadOnly Property Generic_AlwaysDisabled() As String
            Get
                Return ResourceManager.GetString("Generic_AlwaysDisabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Always Enabled ähnelt.
        '''</summary>
        Friend ReadOnly Property Generic_AlwaysEnabled() As String
            Get
                Return ResourceManager.GetString("Generic_AlwaysEnabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        '''</summary>
        Friend ReadOnly Property Generic_Close() As String
            Get
                Return ResourceManager.GetString("Generic_Close", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Dark Theme ähnelt.
        '''</summary>
        Friend ReadOnly Property Generic_DarkTheme() As String
            Get
                Return ResourceManager.GetString("Generic_DarkTheme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Default ähnelt.
        '''</summary>
        Friend ReadOnly Property Generic_Default() As String
            Get
                Return ResourceManager.GetString("Generic_Default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Disabled by Default ähnelt.
        '''</summary>
        Friend ReadOnly Property Generic_DisabledByDefault() As String
            Get
                Return ResourceManager.GetString("Generic_DisabledByDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Done. ähnelt.
        '''</summary>
        Friend ReadOnly Property Generic_Done() As String
            Get
                Return ResourceManager.GetString("Generic_Done", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Enabled By Default ähnelt.
        '''</summary>
        Friend ReadOnly Property Generic_EnabledByDefault() As String
            Get
                Return ResourceManager.GetString("Generic_EnabledByDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Feature ID ähnelt.
        '''</summary>
        Friend ReadOnly Property Generic_FeatureID() As String
            Get
                Return ResourceManager.GetString("Generic_FeatureID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Feature Name ähnelt.
        '''</summary>
        Friend ReadOnly Property Generic_FeatureName() As String
            Get
                Return ResourceManager.GetString("Generic_FeatureName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Feature State ähnelt.
        '''</summary>
        Friend ReadOnly Property Generic_FeatureState() As String
            Get
                Return ResourceManager.GetString("Generic_FeatureState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Light Theme ähnelt.
        '''</summary>
        Friend ReadOnly Property Generic_LightTheme() As String
            Get
                Return ResourceManager.GetString("Generic_LightTheme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Load manually... ähnelt.
        '''</summary>
        Friend ReadOnly Property Generic_LoadManually() As String
            Get
                Return ResourceManager.GetString("Generic_LoadManually", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Modifiable ähnelt.
        '''</summary>
        Friend ReadOnly Property Generic_Modifiable() As String
            Get
                Return ResourceManager.GetString("Generic_Modifiable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Populating the Data Grid View... This can take a while. ähnelt.
        '''</summary>
        Friend ReadOnly Property Generic_PopulatingTheDataGridView() As String
            Get
                Return ResourceManager.GetString("Generic_PopulatingTheDataGridView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Select Build... ähnelt.
        '''</summary>
        Friend ReadOnly Property Generic_SelectBuild() As String
            Get
                Return ResourceManager.GetString("Generic_SelectBuild", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_about_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_about_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_about_96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_about_96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_advertisement_page_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_advertisement_page_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_advertisement_page_96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_advertisement_page_96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_change_theme_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_change_theme_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_moon_and_stars_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_moon_and_stars_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_portrait_mode_scanning_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_portrait_mode_scanning_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_registration_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_registration_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_rollback_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_rollback_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_settings_system_daydream_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_settings_system_daydream_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_start_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_start_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_sun_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_sun_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_toggle_off_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_toggle_off_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_toggle_on_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_toggle_on_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Path to a Feature List ähnelt.
        '''</summary>
        Friend ReadOnly Property LoadManually_PathToAFeatureList() As String
            Get
                Return ResourceManager.GetString("LoadManually_PathToAFeatureList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Friend ReadOnly Property main_icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("main_icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ready. Select a build from the Combo Box to get started, or alternatively press F12 to manually change a Feature. ähnelt.
        '''</summary>
        Friend ReadOnly Property PopulateBuildComboBox_Check_Ready() As String
            Get
                Return ResourceManager.GetString("PopulateBuildComboBox_Check_Ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die  Success ähnelt.
        '''</summary>
        Friend ReadOnly Property SetConfig_Success() As String
            Get
                Return ResourceManager.GetString("SetConfig_Success", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Successfully set Feature {0} to {1} ähnelt.
        '''</summary>
        Friend ReadOnly Property SetConfig_SuccessfullySetFeature() As String
            Get
                Return ResourceManager.GetString("SetConfig_SuccessfullySetFeature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Successfully set Feature Configuration for {0} with Value {1} ähnelt.
        '''</summary>
        Friend ReadOnly Property SetConfig_SuccessfullySetFeatureConfig_Status() As String
            Get
                Return ResourceManager.GetString("SetConfig_SuccessfullySetFeatureConfig_Status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Successfully set Feature ID {0} to {1} ähnelt.
        '''</summary>
        Friend ReadOnly Property SetConfig_SuccessfullySetFeatureID() As String
            Get
                Return ResourceManager.GetString("SetConfig_SuccessfullySetFeatureID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        '''</summary>
        Friend ReadOnly Property settings_system_daydream() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_system_daydream", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &amp;About ähnelt.
        '''</summary>
        Friend ReadOnly Property SystemMenu_About() As String
            Get
                Return ResourceManager.GetString("SystemMenu_About", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Manually Set Feature ID ähnelt.
        '''</summary>
        Friend ReadOnly Property SystemMenu_ManuallySetFeatureID() As String
            Get
                Return ResourceManager.GetString("SystemMenu_ManuallySetFeatureID", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
