'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ViVeTool_GUI.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property about() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("about", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The mismatch of an Assembly Dependency Version has occurred.
        '''
        '''Running ViVeTool GUI directly from a ZIP file without extracting it first or missing/replacing a ViVeTool GUI DLL file can cause this issue..
        '''</summary>
        Friend ReadOnly Property Check_AssemblyVersions_Text() As String
            Get
                Return ResourceManager.GetString("Check_AssemblyVersions_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dependency Version mismatch.
        '''</summary>
        Friend ReadOnly Property Check_AssemblyVersions_Title() As String
            Get
                Return ResourceManager.GetString("Check_AssemblyVersions_Title", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking if the Comments Database Server is available….
        '''</summary>
        Friend ReadOnly Property Comments_CheckingAvailabillity() As String
            Get
                Return ResourceManager.GetString("Comments_CheckingAvailabillity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Closes the Dialog.
        '''</summary>
        Friend ReadOnly Property Comments_ClosesTheDialog() As String
            Get
                Return ResourceManager.GetString("Comments_ClosesTheDialog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your Comment was sent successfully..
        '''</summary>
        Friend ReadOnly Property Comments_CommentSentSuccessfully() As String
            Get
                Return ResourceManager.GetString("Comments_CommentSentSuccessfully", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An Error occurred while communicating with the Comments Database Server.
        '''</summary>
        Friend ReadOnly Property Comments_DBError_CommunicationError() As String
            Get
                Return ResourceManager.GetString("Comments_DBError_CommunicationError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comments couldn&apos;t be loaded, because the Database Server is currently shutting down..
        '''</summary>
        Friend ReadOnly Property Comments_DBError_ShuttingDown() As String
            Get
                Return ResourceManager.GetString("Comments_DBError_ShuttingDown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comments couldn&apos;t be loaded, because the Database Server is currently unavailable..
        '''</summary>
        Friend ReadOnly Property Comments_DBError_Unavailable() As String
            Get
                Return ResourceManager.GetString("Comments_DBError_Unavailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comment for {0}.
        '''</summary>
        Friend ReadOnly Property Comments_DialogTitle() As String
            Get
                Return ResourceManager.GetString("Comments_DialogTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;&lt;p&gt;Press on &quot;&quot;&lt;strong&gt;Edit Text&lt;/strong&gt;&quot;&quot; to edit the Comment Text.&lt;/p&gt;&lt;p&gt;&lt;/p&gt;&lt;p&gt;You can either write a Comment using normal Text, or &lt;strong&gt;&lt;em&gt;HTML-like Text Formatting&lt;/em&gt;&lt;/strong&gt;&lt;/p&gt;&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property Comments_Form_EditIntroducionText() As String
            Get
                Return ResourceManager.GetString("Comments_Form_EditIntroducionText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Getting Feature Comments from the Database….
        '''</summary>
        Friend ReadOnly Property Comments_GettingComments() As String
            Get
                Return ResourceManager.GetString("Comments_GettingComments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I Agree.
        '''</summary>
        Friend ReadOnly Property Comments_I_Agree() As String
            Get
                Return ResourceManager.GetString("Comments_I_Agree", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I Dont Agree.
        '''</summary>
        Friend ReadOnly Property Comments_I_Dont_Agree() As String
            Get
                Return ResourceManager.GetString("Comments_I_Dont_Agree", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close this Dialog and don&apos;t send anything.
        '''</summary>
        Friend ReadOnly Property Comments_I_Dont_Agree_Subtext() As String
            Get
                Return ResourceManager.GetString("Comments_I_Dont_Agree_Subtext", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Privacy Information.
        '''</summary>
        Friend ReadOnly Property Comments_PrivacyInformation() As String
            Get
                Return ResourceManager.GetString("Comments_PrivacyInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;&lt;p&gt;Before you can send your comment, you have to agree that your encrypted IP Address will be stored for a week as part of our &lt;a href=&quot;https://github.com/PeterStrick/ViVeTool-GUI/blob/v1.7-Testing/Comments/privacy.md&quot;&gt;Privacy Policy&lt;/a&gt;, after pressing on &apos;I agree&apos;.&lt;/p&gt;&lt;/html&gt;.
        '''</summary>
        Friend ReadOnly Property Comments_PrivacyText() As String
            Get
                Return ResourceManager.GetString("Comments_PrivacyText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sending your Comment….
        '''</summary>
        Friend ReadOnly Property Comments_SendingYourComment() As String
            Get
                Return ResourceManager.GetString("Comments_SendingYourComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Send my comment.
        '''</summary>
        Friend ReadOnly Property Comments_SendMyComment() As String
            Get
                Return ResourceManager.GetString("Comments_SendMyComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An unknown error occurred while communicating with the Comments Server. {0}.
        '''</summary>
        Friend ReadOnly Property Comments_ServerError_Generic() As String
            Get
                Return ResourceManager.GetString("Comments_ServerError_Generic", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred while communicating with the Comments Server. HTTP 400: Bad Request.
        '''</summary>
        Friend ReadOnly Property Comments_ServerError_HTTP400() As String
            Get
                Return ResourceManager.GetString("Comments_ServerError_HTTP400", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred while communicating with the Comments Server. HTTP 403: Forbidden.
        '''</summary>
        Friend ReadOnly Property Comments_ServerError_HTTP403() As String
            Get
                Return ResourceManager.GetString("Comments_ServerError_HTTP403", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occurred while communicating with the Comments Server. HTTP 404: Not Found.
        '''</summary>
        Friend ReadOnly Property Comments_ServerError_HTTP404() As String
            Get
                Return ResourceManager.GetString("Comments_ServerError_HTTP404", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Comments Server is currently unavailable. HTTP 500: Internal Server Error.
        '''</summary>
        Friend ReadOnly Property Comments_ServerError_HTTP500() As String
            Get
                Return ResourceManager.GetString("Comments_ServerError_HTTP500", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Comments Server is currently unavailable. HTTP 502: Bad Gateway.
        '''</summary>
        Friend ReadOnly Property Comments_ServerError_HTTP502() As String
            Get
                Return ResourceManager.GetString("Comments_ServerError_HTTP502", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Comments Server is currently unavailable. {0}.
        '''</summary>
        Friend ReadOnly Property Comments_ServerError_HTTP503() As String
            Get
                Return ResourceManager.GetString("Comments_ServerError_HTTP503", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Comments Server is currently unavailable. HTTP 504: Gateway Timeout.
        '''</summary>
        Friend ReadOnly Property Comments_ServerError_HTTP504() As String
            Get
                Return ResourceManager.GetString("Comments_ServerError_HTTP504", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Comment Sent.
        '''</summary>
        Friend ReadOnly Property Comments_Spaced_CommentSent() As String
            Get
                Return ResourceManager.GetString("Comments_Spaced_CommentSent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Privacy Information.
        '''</summary>
        Friend ReadOnly Property Comments_Spaced_PrivacyInformation() As String
            Get
                Return ResourceManager.GetString("Comments_Spaced_PrivacyInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Sending your Comment….
        '''</summary>
        Friend ReadOnly Property Comments_Spaced_SendingYourComment() As String
            Get
                Return ResourceManager.GetString("Comments_Spaced_SendingYourComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A Database Error occurred.
        '''</summary>
        Friend ReadOnly Property Error_ADatabaseErrorOccurred() As String
            Get
                Return ResourceManager.GetString("Error_ADatabaseErrorOccurred", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An Error occurred.
        '''</summary>
        Friend ReadOnly Property Error_AnErrorOccurred() As String
            Get
                Return ResourceManager.GetString("Error_AnErrorOccurred", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A Network Error occurred.
        '''</summary>
        Friend ReadOnly Property Error_ANetworkErrorOccurred() As String
            Get
                Return ResourceManager.GetString("Error_ANetworkErrorOccurred", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A Network Exception occurred.
        '''</summary>
        Friend ReadOnly Property Error_ANetworkExceptionOccurred() As String
            Get
                Return ResourceManager.GetString("Error_ANetworkExceptionOccurred", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An Exception occurred.
        '''</summary>
        Friend ReadOnly Property Error_AnExceptionOccurred() As String
            Get
                Return ResourceManager.GetString("Error_AnExceptionOccurred", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An unknown Exception occurred.
        '''</summary>
        Friend ReadOnly Property Error_AnUnknownExceptionOccurred() As String
            Get
                Return ResourceManager.GetString("Error_AnUnknownExceptionOccurred", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Collapse Exception.
        '''</summary>
        Friend ReadOnly Property Error_CollapseException() As String
            Get
                Return ResourceManager.GetString("Error_CollapseException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copies the Exception to the Clipboard and closes the dialog.
        '''</summary>
        Friend ReadOnly Property Error_CopyExceptionAndClose_ToolTip() As String
            Get
                Return ResourceManager.GetString("Error_CopyExceptionAndClose_ToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend ReadOnly Property Error_Error() As String
            Get
                Return ResourceManager.GetString("Error_Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An Exception occurred while trying to set Feature ID {0} to {1}.
        '''</summary>
        Friend ReadOnly Property Error_ExceptionSettingFeatureID() As String
            Get
                Return ResourceManager.GetString("Error_ExceptionSettingFeatureID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An Error occurred while trying to start the ViVeTool GUI Feature Scanner.
        '''
        '''The File doesn&apos;t exist..
        '''</summary>
        Friend ReadOnly Property Error_FeatureScannerNotFound_N() As String
            Get
                Return ResourceManager.GetString("Error_FeatureScannerNotFound_N", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A generic Win32 Exception occurred..
        '''</summary>
        Friend ReadOnly Property Error_GenericWin32Exception_Heading() As String
            Get
                Return ResourceManager.GetString("Error_GenericWin32Exception_Heading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There could be multiple causes for Win32 Exceptions, but they usually narrow down to Anti-virus Software interfering with ViVeTool GUI, or Permission problems..
        '''</summary>
        Friend ReadOnly Property Error_GenericWin32Exception_Text() As String
            Get
                Return ResourceManager.GetString("Error_GenericWin32Exception_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Network Error.
        '''</summary>
        Friend ReadOnly Property Error_NetworkError() As String
            Get
                Return ResourceManager.GetString("Error_NetworkError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your IP may have been temporarily rate limited by the GitHub API for an hour..
        '''</summary>
        Friend ReadOnly Property Error_NetworkException_GithubAPI() As String
            Get
                Return ResourceManager.GetString("Error_NetworkException_GithubAPI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GitHub API Response: .
        '''</summary>
        Friend ReadOnly Property Error_NetworkException_GithubAPI_Response() As String
            Get
                Return ResourceManager.GetString("Error_NetworkException_GithubAPI_Response", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ViVeTool-GUI is unable to populate the Build Combo Box, if the Device isn&apos;t connected to the Internet, or if the GitHub API is unreachable.
        '''
        '''You are still able to manually change a Feature ID by pressing F12, and able to load a local Feature List..
        '''</summary>
        Friend ReadOnly Property Error_NetworkExceptionDetail_N() As String
            Get
                Return ResourceManager.GetString("Error_NetworkExceptionDetail_N", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Network Functions disabled. Press F12 to manually change a Feature..
        '''</summary>
        Friend ReadOnly Property Error_NetworkFunctionsDisabledF12() As String
            Get
                Return ResourceManager.GetString("Error_NetworkFunctionsDisabledF12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Build 17704 or higher to use Grouping.
        '''</summary>
        Friend ReadOnly Property Error_SelectBuild17704OrHigherToUseGrouping() As String
            Get
                Return ResourceManager.GetString("Error_SelectBuild17704OrHigherToUseGrouping", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An Error occurred while sending your comment..
        '''</summary>
        Friend ReadOnly Property Error_SendComment() As String
            Get
                Return ResourceManager.GetString("Error_SendComment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Restart without sending a Crash Report.
        '''</summary>
        Friend ReadOnly Property Error_Sentry_RestartWithoutReportingBtn_Text() As String
            Get
                Return ResourceManager.GetString("Error_Sentry_RestartWithoutReportingBtn_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Send Crash Report and Restart.
        '''</summary>
        Friend ReadOnly Property Error_Sentry_SendAndReportBtn_Text() As String
            Get
                Return ResourceManager.GetString("Error_Sentry_SendAndReportBtn_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to send a Crash Report and restart the Application?.
        '''</summary>
        Friend ReadOnly Property Error_Sentry_Text() As String
            Get
                Return ResourceManager.GetString("Error_Sentry_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An Error occurred while trying to set {0} to {1}.
        '''</summary>
        Friend ReadOnly Property Error_SetConfig() As String
            Get
                Return ResourceManager.GetString("Error_SetConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An Error occurred while setting a feature configuration for {0}.
        '''</summary>
        Friend ReadOnly Property Error_SettingFeatureConfig() As String
            Get
                Return ResourceManager.GetString("Error_SettingFeatureConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show Exception.
        '''</summary>
        Friend ReadOnly Property Error_ShowException() As String
            Get
                Return ResourceManager.GetString("Error_ShowException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unsupported Build.
        '''</summary>
        Friend ReadOnly Property Error_UnsupportedBuild() As String
            Get
                Return ResourceManager.GetString("Error_UnsupportedBuild", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are running an unsupported Windows 10 Build. ViVe, ViVeTool and ViVeTool GUI require Windows 10 Build 18963 or higher to function properly. Your Build is: {0}.
        '''</summary>
        Friend ReadOnly Property Error_UnsupportedBuild_Text_N() As String
            Get
                Return ResourceManager.GetString("Error_UnsupportedBuild_Text_N", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The download of a more recent Feature Dictionary has completed successfully..
        '''</summary>
        Friend ReadOnly Property FeatureDictionary_DownloadText() As String
            Get
                Return ResourceManager.GetString("FeatureDictionary_DownloadText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download completed.
        '''</summary>
        Friend ReadOnly Property FeatureDictionary_DownloadTitle() As String
            Get
                Return ResourceManager.GetString("FeatureDictionary_DownloadTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Feature Dictionary provides a translation between ViVeTool Feature Names and ViVeTool IDs. Although optional, it is recommended to download this Dictionary. Would you like to download it now?.
        '''</summary>
        Friend ReadOnly Property FeatureDictionary_MissingText() As String
            Get
                Return ResourceManager.GetString("FeatureDictionary_MissingText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Feature Dictionary is missing.
        '''</summary>
        Friend ReadOnly Property FeatureDictionary_MissingTitle() As String
            Get
                Return ResourceManager.GetString("FeatureDictionary_MissingTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An Update Check of the Feature Dictionary could not be performed..
        '''</summary>
        Friend ReadOnly Property FeatureDictionary_UpdateError() As String
            Get
                Return ResourceManager.GetString("FeatureDictionary_UpdateError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A newer Version of the Feature Dictionary is available. It contains translations of newer ViVeTool IDs to their corresponding Feature Name. Do you want to update to it now?.
        '''</summary>
        Friend ReadOnly Property FeatureDictionary_UpdateText() As String
            Get
                Return ResourceManager.GetString("FeatureDictionary_UpdateText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A Feature Dictionary Update is available.
        '''</summary>
        Friend ReadOnly Property FeatureDictionary_UpdateTitle() As String
            Get
                Return ResourceManager.GetString("FeatureDictionary_UpdateTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finish.
        '''</summary>
        Friend ReadOnly Property General_Finish() As String
            Get
                Return ResourceManager.GetString("General_Finish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Always Disabled.
        '''</summary>
        Friend ReadOnly Property Generic_AlwaysDisabled() As String
            Get
                Return ResourceManager.GetString("Generic_AlwaysDisabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Always Enabled.
        '''</summary>
        Friend ReadOnly Property Generic_AlwaysEnabled() As String
            Get
                Return ResourceManager.GetString("Generic_AlwaysEnabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Friend ReadOnly Property Generic_Close() As String
            Get
                Return ResourceManager.GetString("Generic_Close", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Copy.
        '''</summary>
        Friend ReadOnly Property Generic_Copy() As String
            Get
                Return ResourceManager.GetString("Generic_Copy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dark Theme.
        '''</summary>
        Friend ReadOnly Property Generic_DarkTheme() As String
            Get
                Return ResourceManager.GetString("Generic_DarkTheme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default.
        '''</summary>
        Friend ReadOnly Property Generic_Default() As String
            Get
                Return ResourceManager.GetString("Generic_Default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disabled by Default.
        '''</summary>
        Friend ReadOnly Property Generic_DisabledByDefault() As String
            Get
                Return ResourceManager.GetString("Generic_DisabledByDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Done..
        '''</summary>
        Friend ReadOnly Property Generic_Done() As String
            Get
                Return ResourceManager.GetString("Generic_Done", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enabled By Default.
        '''</summary>
        Friend ReadOnly Property Generic_EnabledByDefault() As String
            Get
                Return ResourceManager.GetString("Generic_EnabledByDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Feature ID.
        '''</summary>
        Friend ReadOnly Property Generic_FeatureID() As String
            Get
                Return ResourceManager.GetString("Generic_FeatureID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Feature List.
        '''</summary>
        Friend ReadOnly Property Generic_FeatureList() As String
            Get
                Return ResourceManager.GetString("Generic_FeatureList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Feature Mgmt.
        '''</summary>
        Friend ReadOnly Property Generic_FeatureManagement() As String
            Get
                Return ResourceManager.GetString("Generic_FeatureManagement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Feature Name.
        '''</summary>
        Friend ReadOnly Property Generic_FeatureName() As String
            Get
                Return ResourceManager.GetString("Generic_FeatureName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Feature State.
        '''</summary>
        Friend ReadOnly Property Generic_FeatureState() As String
            Get
                Return ResourceManager.GetString("Generic_FeatureState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Light Theme.
        '''</summary>
        Friend ReadOnly Property Generic_LightTheme() As String
            Get
                Return ResourceManager.GetString("Generic_LightTheme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load manually….
        '''</summary>
        Friend ReadOnly Property Generic_LoadManually() As String
            Get
                Return ResourceManager.GetString("Generic_LoadManually", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modifiable.
        '''</summary>
        Friend ReadOnly Property Generic_Modifiable() As String
            Get
                Return ResourceManager.GetString("Generic_Modifiable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nothing.
        '''</summary>
        Friend ReadOnly Property Generic_Nothing() As String
            Get
                Return ResourceManager.GetString("Generic_Nothing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not required.
        '''</summary>
        Friend ReadOnly Property Generic_NotRequired() As String
            Get
                Return ResourceManager.GetString("Generic_NotRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Populating the Data Grid View… This can take a while..
        '''</summary>
        Friend ReadOnly Property Generic_PopulatingTheDataGridView() As String
            Get
                Return ResourceManager.GetString("Generic_PopulatingTheDataGridView", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Build….
        '''</summary>
        Friend ReadOnly Property Generic_SelectBuild() As String
            Get
                Return ResourceManager.GetString("Generic_SelectBuild", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version {0}.
        '''</summary>
        Friend ReadOnly Property Generic_Version() As String
            Get
                Return ResourceManager.GetString("Generic_Version", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_about_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_about_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_about_96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_about_96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_advertisement_page_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_advertisement_page_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_advertisement_page_96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_advertisement_page_96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_change_theme_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_change_theme_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_comments_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_comments_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_dictionary_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_dictionary_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_moon_and_stars_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_moon_and_stars_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_portrait_mode_scanning_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_portrait_mode_scanning_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_registration_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_registration_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_rollback_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_rollback_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_settings_system_daydream_24px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_settings_system_daydream_24px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_start_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_start_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_sun_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_sun_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_tick_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_tick_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_time_machine_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_time_machine_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_toggle_off_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_toggle_off_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_toggle_on_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_toggle_on_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_update_24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8_update_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language Change requires restart.
        '''</summary>
        Friend ReadOnly Property Language_Heading() As String
            Get
                Return ResourceManager.GetString("Language_Heading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ViVeTool GUI needs to restart to reflect the Language change.
        '''
        '''It will try to restart after you press on Close..
        '''</summary>
        Friend ReadOnly Property Language_Text() As String
            Get
                Return ResourceManager.GetString("Language_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Path to a Feature List.
        '''</summary>
        Friend ReadOnly Property LoadManually_PathToAFeatureList() As String
            Get
                Return ResourceManager.GetString("LoadManually_PathToAFeatureList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property main_icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("main_icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ready. Select a build from the Combo Box to get started, or alternatively press F12 to manually change a Feature..
        '''</summary>
        Friend ReadOnly Property PopulateBuildComboBox_Check_Ready() As String
            Get
                Return ResourceManager.GetString("PopulateBuildComboBox_Check_Ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Populating the Build Combo Box….
        '''</summary>
        Friend ReadOnly Property PopulateBuildComboBox_Populating() As String
            Get
                Return ResourceManager.GetString("PopulateBuildComboBox_Populating", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  Success.
        '''</summary>
        Friend ReadOnly Property SetConfig_Success() As String
            Get
                Return ResourceManager.GetString("SetConfig_Success", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Successfully set Feature {0} to {1}.
        '''</summary>
        Friend ReadOnly Property SetConfig_SuccessfullySetFeature() As String
            Get
                Return ResourceManager.GetString("SetConfig_SuccessfullySetFeature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Successfully set Feature Configuration for {0} with Value {1}.
        '''</summary>
        Friend ReadOnly Property SetConfig_SuccessfullySetFeatureConfig_Status() As String
            Get
                Return ResourceManager.GetString("SetConfig_SuccessfullySetFeatureConfig_Status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Successfully set Feature ID {0} to {1}.
        '''</summary>
        Friend ReadOnly Property SetConfig_SuccessfullySetFeatureID() As String
            Get
                Return ResourceManager.GetString("SetConfig_SuccessfullySetFeatureID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property settings_system_daydream() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("settings_system_daydream", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The current Build Feature List.
        '''</summary>
        Friend ReadOnly Property Settings_TheCurrentBuildFeatureList() As String
            Get
                Return ResourceManager.GetString("Settings_TheCurrentBuildFeatureList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The latest Build Feature List.
        '''</summary>
        Friend ReadOnly Property Settings_TheLatestBuildFeatureList() As String
            Get
                Return ResourceManager.GetString("Settings_TheLatestBuildFeatureList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;About.
        '''</summary>
        Friend ReadOnly Property SystemMenu_About() As String
            Get
                Return ResourceManager.GetString("SystemMenu_About", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Manually Set Feature ID.
        '''</summary>
        Friend ReadOnly Property SystemMenu_ManuallySetFeatureID() As String
            Get
                Return ResourceManager.GetString("SystemMenu_ManuallySetFeatureID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Abort.
        '''</summary>
        Friend ReadOnly Property Telerik_Abort() As String
            Get
                Return ResourceManager.GetString("Telerik_Abort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All.
        '''</summary>
        Friend ReadOnly Property Telerik_All() As String
            Get
                Return ResourceManager.GetString("Telerik_All", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend ReadOnly Property Telerik_Cancel() As String
            Get
                Return ResourceManager.GetString("Telerik_Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Continue.
        '''</summary>
        Friend ReadOnly Property Telerik_Continue() As String
            Get
                Return ResourceManager.GetString("Telerik_Continue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter text to search.
        '''</summary>
        Friend ReadOnly Property Telerik_EnterTextToSearch() As String
            Get
                Return ResourceManager.GetString("Telerik_EnterTextToSearch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help.
        '''</summary>
        Friend ReadOnly Property Telerik_Help() As String
            Get
                Return ResourceManager.GetString("Telerik_Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hide details.
        '''</summary>
        Friend ReadOnly Property Telerik_HideDetails() As String
            Get
                Return ResourceManager.GetString("Telerik_HideDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ignore.
        '''</summary>
        Friend ReadOnly Property Telerik_Ignore() As String
            Get
                Return ResourceManager.GetString("Telerik_Ignore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Master template.
        '''</summary>
        Friend ReadOnly Property Telerik_MasterTemplate() As String
            Get
                Return ResourceManager.GetString("Telerik_MasterTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Match case.
        '''</summary>
        Friend ReadOnly Property Telerik_MatchCase() As String
            Get
                Return ResourceManager.GetString("Telerik_MatchCase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No.
        '''</summary>
        Friend ReadOnly Property Telerik_No() As String
            Get
                Return ResourceManager.GetString("Telerik_No", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to of.
        '''</summary>
        Friend ReadOnly Property Telerik_Of() As String
            Get
                Return ResourceManager.GetString("Telerik_Of", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend ReadOnly Property Telerik_OK() As String
            Get
                Return ResourceManager.GetString("Telerik_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Retry.
        '''</summary>
        Friend ReadOnly Property Telerik_Retry() As String
            Get
                Return ResourceManager.GetString("Telerik_Retry", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search from current position.
        '''</summary>
        Friend ReadOnly Property Telerik_SearchFromCurrentPosition() As String
            Get
                Return ResourceManager.GetString("Telerik_SearchFromCurrentPosition", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search in columns.
        '''</summary>
        Friend ReadOnly Property Telerik_SearchInColumns() As String
            Get
                Return ResourceManager.GetString("Telerik_SearchInColumns", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to See details.
        '''</summary>
        Friend ReadOnly Property Telerik_SeeDetails() As String
            Get
                Return ResourceManager.GetString("Telerik_SeeDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Try Again.
        '''</summary>
        Friend ReadOnly Property Telerik_TryAgain() As String
            Get
                Return ResourceManager.GetString("Telerik_TryAgain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yes.
        '''</summary>
        Friend ReadOnly Property Telerik_Yes() As String
            Get
                Return ResourceManager.GetString("Telerik_Yes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ID is missing. Create a GitHub Issue and include the following Text: {0}.
        '''</summary>
        Friend ReadOnly Property TelerikLocalization_MissingID() As String
            Get
                Return ResourceManager.GetString("TelerikLocalization_MissingID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fixing of the Last Known Good Store is not required..
        '''</summary>
        Friend ReadOnly Property ViVe_LKGStore_NotRequired() As String
            Get
                Return ResourceManager.GetString("ViVe_LKGStore_NotRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Last Known Good Store was successfully repaired..
        '''</summary>
        Friend ReadOnly Property ViVe_LKGStore_Repaired() As String
            Get
                Return ResourceManager.GetString("ViVe_LKGStore_Repaired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The Functions returned {0}. Expected 00.
        '''</summary>
        Friend ReadOnly Property ViVe_Priorities_Error_Expanded() As String
            Get
                Return ResourceManager.GetString("ViVe_Priorities_Error_Expanded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An Error occurred while trying to fix the Feature Priorities..
        '''</summary>
        Friend ReadOnly Property ViVe_Priorities_Error_Text() As String
            Get
                Return ResourceManager.GetString("ViVe_Priorities_Error_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Feature Priorities were successfully fixed. A reboot is recommended..
        '''</summary>
        Friend ReadOnly Property ViVe_Priorities_Fixed() As String
            Get
                Return ResourceManager.GetString("ViVe_Priorities_Fixed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fixing of Feature Priorities is not required..
        '''</summary>
        Friend ReadOnly Property ViVe_Priorities_NotRequired() As String
            Get
                Return ResourceManager.GetString("ViVe_Priorities_NotRequired", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
